"""
Bias Correction Module — LSTM v2

Loads bias tables from JSON (generated by 03_model_evaluation.ipynb).
Supports both simple (hour × dow) and seasonal (hour × dow × season)
correction methods; the JSON specifies which method was chosen.
"""

import json
from pathlib import Path
from typing import Optional

import pandas as pd

BASE_DIR  = Path(__file__).parent.parent.parent
MODEL_DIR = BASE_DIR / 'training' / 'models'
BIAS_JSON = MODEL_DIR / 'lstm_bias_table.json'

# ── Month → season mapping ───────────────────────────────────────────────────
_MONTH_TO_SEASON = {
    12: 'Winter', 1: 'Winter', 2: 'Winter',
    3: 'Spring',  4: 'Spring', 5: 'Spring',
    6: 'Summer',  7: 'Summer', 8: 'Summer',
    9: 'Autumn', 10: 'Autumn', 11: 'Autumn',
}


def _load_bias_tables() -> dict:
    """Load bias table JSON once at import time."""
    if not BIAS_JSON.exists():
        return {
            'chosen_method': 'none',
            'simple_bias': {},
            'seasonal_bias': {},
        }
    with open(BIAS_JSON) as f:
        return json.load(f)


_BIAS = _load_bias_tables()

# Parse simple table: "hour,dow" → float
_SIMPLE: dict[tuple[int, int], float] = {}
for k, v in _BIAS.get('simple_bias', {}).items():
    h, d = k.split(',')
    _SIMPLE[(int(h), int(d))] = float(v)

# Parse seasonal table: "hour,dow,season" → float
_SEASONAL: dict[tuple[int, int, str], float] = {}
for k, v in _BIAS.get('seasonal_bias', {}).items():
    parts = k.split(',')
    _SEASONAL[(int(parts[0]), int(parts[1]), parts[2])] = float(v)

CHOSEN_METHOD: str = _BIAS.get('chosen_method', 'simple')


def get_bias_correction(hour: int, dow: int,
                        month: Optional[int] = None) -> float:
    """Get correction value for a single timestamp.

    Returns the **negative** of the estimated bias so that:
        corrected = prediction + correction
    """
    if CHOSEN_METHOD == 'seasonal' and month is not None:
        season = _MONTH_TO_SEASON.get(month, 'Winter')
        bias = _SEASONAL.get((hour, dow, season),
                             _SIMPLE.get((hour, dow), 0.0))
    else:
        bias = _SIMPLE.get((hour, dow), 0.0)
    return -bias


def apply_bias_correction(
    predictions: pd.DataFrame,
    timestamp_col: str = 'timestamp',
    prediction_col: str = 'predicted_demand',
) -> pd.DataFrame:
    """Apply bias correction to a predictions DataFrame.

    Adds columns: bias_correction, corrected_demand.
    """
    df = predictions.copy()
    ts = pd.to_datetime(df[timestamp_col])

    df['bias_correction'] = [
        get_bias_correction(t.hour, t.dayofweek, t.month) for t in ts
    ]
    df['corrected_demand'] = df[prediction_col] + df['bias_correction']
    return df
